services:

#==========

  maria_db:
    image: mariadb:12
    container_name: mariadb_db
    hostname: mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
    volumes:
      - ${DB_PATH}/mysql:/var/lib/mysql
    networks:
      - stack-network
    ports:
      - '3306:3306'
    restart: unless-stopped

#----------

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin_ui
    environment:
      PMA_HOST: maria_db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      UPLOAD_LIMIT: 1G
    ports:
      - '8080:80'
    networks:
      - stack-network
    depends_on:
      - maria_db
    restart: unless-stopped

#==========

networks:

  stack-network:
    name: stack-network
    driver: bridge